"""Constants for Watch Sensors Pro."""

DOMAIN = "ha_companion"

# Definición de todos los sensores
SENSORS = [
    {
        "key": "battery",
        "translation_key": "Battery",
        "attribute": "battery_state",
        "unit": "%",
        "device_class": "battery",
        "icon": "mdi:battery",
        "state_class": "measurement"
    },
    {
        "key": "steps",
        "translation_key": "Steps",
        "attribute": "steps_state",
        "unit": "steps",
        "icon": "mdi:walk",
        "state_class": "total_increasing"
    },
    {
        "key": "steps_target",
        "translation_key": "Steps Daily Target",
        "attribute": "steps_daily_target",
        "unit": "steps",
        "icon": "mdi:flag-checkered",
        "state_class": "measurement"
    },    
    {
        "key": "heart_rate",
        "translation_key": "Heart Rate",
        "attribute": "heart_state",
        "unit": "bpm",
        "device_class": "heart_rate",
        "icon": "mdi:heart-pulse",
        "state_class": "measurement"
    },
    {
        "key": "heart_max",
        "translation_key": "Heart Rate Max",
        "attribute": "heart_daily_summary",
        "unit": "bpm",
        "device_class": "heart_rate",
        "icon": "mdi:heart-flash",
        "state_class": "measurement",
        "json_extract": "maximum.hr_value"  
    },
    {
        "key": "heart_resting",
        "translation_key": "Resting Heart Rate",
        "attribute": "heart_resting",
        "unit": "bpm",
        "device_class": "heart_rate",
        "icon": "mdi:heart-pulse",
        "state_class": "measurement"
    },    
    {
        "key": "spo2",
        "translation_key": "Blood Oxygen",
        "attribute": "spo2_state",
        "unit": "%",
        "icon": "mdi:lungs",
        "state_class": "measurement",
        "json_extract": "value"
    },
    {
        "key": "calories",
        "translation_key": "Calories",
        "attribute": "calorie_state",
        "unit": "kcal",
        "device_class": "energy",
        "icon": "mdi:fire",
        "state_class": "total_increasing"
    },
    {
        "key": "calories_target",
        "translation_key": "Calories Target",
        "attribute": "calories_burnt_target",
        "unit": "kcal",
        "device_class": "energy",
        "icon": "mdi:fire-circle",
        "state_class": "measurement"
    },    
    {
        "key": "distance",
        "translation_key": "Distance",
        "attribute": "distance_state",
        "unit": "m",
        "device_class": "distance",
        "icon": "mdi:map-marker-distance",
        "state_class": "total_increasing"
    },
    {
        "key": "stand_hours",
        "translation_key": "Stand Hours",
        "attribute": "stand_state",
        "unit": "h",
        "icon": "mdi:human",
        "state_class": "measurement"
    },
    {
        "key": "stand_hours_target",
        "translation_key": "Stand Hours Target",
        "attribute": "stand_hours_target",
        "unit": "h",
        "icon": "mdi:human-handsup",
        "state_class": "measurement"
    },    
    {
        "key": "fat_burning",
        "translation_key": "Fat Burning",
        "attribute": "fat_burning_state",
        "unit": "min",
        "icon": "mdi:fire-circle",
        "state_class": "measurement"
    },
    {
        "key": "fat_burning_target",
        "translation_key": "Fat Burning Target",
        "attribute": "fat_burning_minutes_target",
        "unit": "min",
        "icon": "mdi:fire-circle",
        "state_class": "measurement"
    },    
    {
        "key": "pai",
        "translation_key": "PAI Score",
        "attribute": "pai_state",
        "unit": "PAI",
        "icon": "mdi:chart-line",
        "state_class": "measurement"
    },
    {
        "key": "pai_total",
        "translation_key": "PAI Total",
        "attribute": "pai_total",
        "unit": "PAI",
        "icon": "mdi:chart-line",
        "state_class": "total_increasing"
    },    
    {
        "key": "temperature",
        "translation_key": "Body Temperature",
        "attribute": "temperature_state",
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "state_class": "measurement",
        "json_extract": "value",
        "value_convert": 0.01  # ← 3318 * 0.01 = 33.18°C
    },
    {
        "key": "sleep_status",
        "translation_key": "Sleep Status",
        "attribute": "sleep_state",
        "icon": "mdi:sleep"
    },
    {
        "key": "sleep_score",
        "translation_key": "Sleep Score",
        "attribute": "sleep_info",
        "unit": "points",
        "icon": "mdi:sleep",
        "state_class": "measurement",
        "json_extract": "score"
    },
    {
        "key": "sleep_total_time",
        "translation_key": "Sleep Total Time", 
        "attribute": "sleep_info",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:bed-clock",
        "state_class": "measurement",
        "json_extract": "totalTime"
    },
    {
        "key": "sleep_deep_time",
        "translation_key": "Sleep Deep Time",
        "attribute": "sleep_info",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:bed",
        "state_class": "measurement",
        "json_extract": "deepTime"
    },
    {
        "key": "sleep_start_time",
        "translation_key": "Sleep Start Time",
        "attribute": "sleep_info",
        "icon": "mdi:weather-night",
        "json_extract": "startTime",
        "time_convert": True   
    },
    {
        "key": "sleep_end_time",
        "translation_key": "Sleep End Time",
        "attribute": "sleep_info",
        "icon": "mdi:weather-sunny",
        "json_extract": "endTime",
        "time_convert": True   
    },
    {
        "key": "sleep_deep_minutes",
        "translation_key": "Sleep Deep Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:sleep",
        "state_class": "measurement",
        "sleep_stage_extract": "DEEP_STAGE"
    },
    {
        "key": "sleep_rem_minutes",
        "translation_key": "Sleep REM Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:brain",
        "state_class": "measurement",
        "sleep_stage_extract": "REM_STAGE"
    },
    {
        "key": "sleep_light_minutes",
        "translation_key": "Sleep Light Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:weather-night-partly-cloudy",
        "state_class": "measurement",
        "sleep_stage_extract": "LIGHT_STAGE"
    },
    {
        "key": "sleep_wake_minutes",
        "translation_key": "Sleep Wake Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:eye",
        "state_class": "measurement",
        "sleep_stage_extract": "WAKE_STAGE"
    },
    {
        "key": "stress",
        "name": "Stress",
        "attribute": "stress_state",
        "icon": "mdi:emoticon-happy",
        "state_class": "measurement",
        "json_extract": "value"
    },
    {
        "key": "wear",
        "name": "Wear Status",
        "attribute": "wear_state",
        "icon": "mdi:watch",
    },
    {
        "key": "user_age",
        "translation_key": "Age",
        "attribute": "user_age",
        "icon": "mdi:account",
    },
    {
        "key": "user_height",
        "translation_key": "Height",
        "attribute": "user_height",
        "icon": "mdi:human-male-height",
        "unit": "m",
    },
    {
        "key": "user_weight",
        "translation_key": "Weight",
        "attribute": "user_weight",
        "icon": "mdi:weight-kilogram",
        "unit": "kg",
    },
    {
        "key": "user_gender",
        "translation_key": "Gender",
        "attribute": "user_gender",
        "icon": "mdi:gender-male-female",
    },
    {
        "key": "user_region",
        "translation_key": "Region",
        "attribute": "user_region",
        "icon": "mdi:earth",
    },
    {
        "key": "workout_last_date",
        "translation_key": "Last Workout Date",
        "attribute": "workout_last_date",
        "icon": "mdi:calendar-clock",
        "time_convert": True,
    },
    {
        "key": "workout_last_duration",
        "translation_key": "Last Workout Duration",
        "attribute": "workout_last_duration",
        "icon": "mdi:timer-outline",
        "unit": "min",
    },
    {
        "key": "workout_last_sport_type",
        "translation_key": "Last Sport Type",
        "attribute": "workout_last_sport_type",
        "icon": "mdi:run",
    },
    {
        "key": "workout_training_load",
        "translation_key": "Training Load",
        "attribute": "workout_training_load",
        "icon": "mdi:weight-lifter",
    },
    {
        "key": "workout_vo2_max",
        "translation_key": "VO2 Max",
        "attribute": "workout_vo2_max",
        "icon": "mdi:lungs",
        "unit": "ml/kg/min",
    },
    {
        "key": "workout_count",
        "translation_key": "Workout Count",
        "attribute": "workout_count",
        "icon": "mdi:counter",
    },
    {
        "key": "altitude_state",
        "translation_key": "altitude_state",
        "attribute": "altitude_state",
        "icon": "mdi:elevation-rise",
        "unit": "m",
    },
    {
        "key": "air_pressure_state",
        "translation_key": "air_pressure_state",
        "attribute": "air_pressure_state",
        "icon": "mdi:gauge",
        "unit": "hPa",
    },
]

SPORT_TYPES = {
    1001: "Outdoor Running", 
    1002: "Treadmill", 
    1003: "Walking",
    1004: "Outdoor Cycling", 
    1005: "Free Training", 
    1006: "Pool Swimming",
    1007: "Open Water Swimming", 
    1008: "Indoor Riding", 
    1009: "Elliptical Machine",
    1010: "Mountaineering",
    1011: "Cross Country Running", 
    1012: "Skiing",
    1015: "Outdoor Hiking", 
    1017: "Tennis", 
    1018: "Football",
    1019: "Ironman Triathlon", 
    1020: "Compound Motion", 
    1021: "Jump Rope",
    1023: "Rowing Machine",
    1024: "Indoor Fitness", 
    1040: "Indoor Walking",
    1041: "Curling", 
    1042: "Snowboarding", 
    1043: "Alpine Skiing",
    1044: "Outdoor Skating", 
    1045: "Indoor Skating", 
    1046: "Cross-Country Skiing",
    1047: "Mountain Cycling", 
    1048: "BMX", 
    1049: "HIIT",
    1050: "Core Training", 
    1051: "Mixed Aerobic", 
    1052: "Strength Training",
    1053: "Stretching", 
    1054: "Climber", 
    1055: "Flexibility Training",
    1057: "Step Training", 
    1058: "Stepper", 
    1059: "Gymnastics",
    1060: "Yoga", 
    1061: "Pilates", 
    1062: "Surfing",
    1063: "Hunting", 
    1064: "Fishing", 
    1065: "Sailing",
    1066: "Outdoor Boating", 
    1067: "Skateboard", 
    1068: "Paddleboarding",
    1069: "Roller Skating", 
    1070: "Rock Climbing", 
    1071: "Ballet",
    1072: "Belly Dance", 
    1073: "Square Dance", 
    1074: "Street Dance",
    1075: "Ballroom Dance", 
    1076: "Dance", 
    1077: "Zumba",
    1078: "Cricket", 
    1079: "Baseball", 
    1080: "Bowling",
    1081: "Squash", 
    1082: "Rugby", 
    1083: "Golf",
    1084: "Golf Swing",
    1085: "Basketball", 
    1086: "Softball",
    1087: "Gateball", 
    1088: "Volleyball", 
    1089: "Ping Pong",
    1090: "Hockey", 
    1091: "Handball", 
    1092: "Badminton",
    1093: "Archery", 
    1094: "Equestrian Sports", 
    1095: "Swordsmanship",
    1096: "Karate", 
    1097: "Boxing", 
    1098: "Judo",
    1099: "Wrestling", 
    1100: "Tai Chi", 
    1101: "Muay Thai",
    1102: "Taekwondo", 
    1103: "Martial Arts", 
    1104: "Free Fighting",
    1105: "Snowboarding", 
    1106: "Kitesurfing", 
    1108: "Climb the Stairs",
    1109: "Fitness", 
    1110: "Orienteering", 
    1111: "Group Exercise",
    1112: "Latin Dance", 
    1113: "Jazz Dance", 
    1114: "Combat Exercise",
    1115: "Hula Hoop", 
    1116: "Frisbee", 
    1117: "Dart",
    1118: "Flying a Kite",
    1119: "Tug-of-war", 
    1120: "Kicking Shuttlecock",
    1121: "Beach Football",
    1122: "Beach Volleyball", 
    1123: "Drifting",
    1124: "Motorboat", 
    1125: "Bicycle", 
    1126: "Sled",
    1128: "Winter Biathlon", 
    1129: "Parkour", 
    1130: "Cross-training",
    1131: "Race Walking", 
    1132: "Driving", 
    1133: "Paragliding",
    1134: "One Minute Sit-ups", 
    1135: "One Minute Skipping Rope",
    1136: "Snowmobile", 
    1137: "Off-Road Motorcycle", 
    1138: "Dragon Boat",
    1139: "Water Ski", 
    1140: "Kayaking", 
    1141: "Rowing",
    1142: "Polo", 
    1143: "Spinning Bike",
    1144: "Walking Machine",
    1145: "Racquetball", 
    1146: "Folk Dance", 
    1147: "Jiu-Jitsu",
    1148: "Fencing", 
    1149: "Horizontal Bar", 
    1150: "Parallel Bars",
    1151: "Billiards", 
    1152: "Sepak Takraw", 
    1153: "Dodgeball",
    1154: "Water Polo", 
    1155: "Fin Swimming", 
    1156: "Synchronized Swimming",
    1157: "Snorkeling", 
    1158: "Ice Hockey", 
    1159: "Swing",
    1160: "Shuffleboard", 
    1161: "Table Football", 
    1162: "Shuttlecock",
    1163: "Somatosensory Games", 
    1164: "Indoor Football", 
    1165: "Hip Hop Dance",
    1166: "Pole Dance", 
    1167: "Battle Rope", 
    1168: "Break Dance",
    1169: "Sandbag Ball", 
    1170: "Bocce", 
    1171: "Pull Back the Ball",
    1172: "Indoor Surfing", 
    1173: "Chess", 
    1174: "Checkers",
    1175: "Go", 
    1176: "Bridge", 
    1177: "Board Game",
    1178: "Snowshoe Hiking", 
    1179: "Shooting", 
    1180: "Skydiving",
    1181: "Downhill", 
    1182: "Bungee Jumping", 
    1183: "Trampoline",
    1184: "Bouldering", 
    1185: "Modern Dance", 
    1186: "Disco",
    1187: "Tap Dance",
    1188: "Floor Ball", 
    1189: "Electronic Sports",
    1190: "ATV",
    1191: "Football (without GPS)", 
    1192: "Playground Running",
    1193: "Fishing (Number of Fishes)",
    1194: "Indoor Rock Climbing",
    1195: "Mountaineering and Skiing",
    1196: "Outdoor Freediving",
    1197: "Indoor Freediving", 
    1198: "Fishing and Hunting",
    1199: "Simple Tennis", 
    1200: "Wakewave Surfing",
    1201: "Surfing (identify number of trips)",
    1202: "Kitesurfing (Identification Gliding)", 
    1203: "Ultra Marathon",
}

