"""Constants for Watch Sensors Pro."""

DOMAIN = "ha_companion"

WEAR_STATES = {
    0: "not_wearing",
    1: "is_wearing",
    2: "in_motion",
    3: "not_sure",
}

# Human-readable sleep-phase names for the sleep_timeline sensor's `timeline`
# attribute. This lives inside a nested list, not the entity's own state, so HA's
# usual strings.json state-translation lookup (see WEAR_STATES above) doesn't reach
# it — WatchSleepTimelineSensor picks the row keyed by hass.config.language instead.
SLEEP_PHASE_LABELS = {
    "es": {
        "WAKE_STAGE": "Despierto",
        "REM_STAGE": "REM",
        "LIGHT_STAGE": "Sueño Ligero",
        "DEEP_STAGE": "Sueño Profundo",
    },
    "en": {
        "WAKE_STAGE": "Awake",
        "REM_STAGE": "REM",
        "LIGHT_STAGE": "Light Sleep",
        "DEEP_STAGE": "Deep Sleep",
    },
    "fr": {
        "WAKE_STAGE": "Éveillé",
        "REM_STAGE": "REM",
        "LIGHT_STAGE": "Sommeil léger",
        "DEEP_STAGE": "Sommeil profond",
    },
    "de": {
        "WAKE_STAGE": "Wach",
        "REM_STAGE": "REM",
        "LIGHT_STAGE": "Leichter Schlaf",
        "DEEP_STAGE": "Tiefschlaf",
    },
    "it": {
        "WAKE_STAGE": "Sveglio",
        "REM_STAGE": "REM",
        "LIGHT_STAGE": "Sonno leggero",
        "DEEP_STAGE": "Sonno profondo",
    },
}

# Definición de todos los sensores
SENSORS = [
    {
        "key": "battery",
        "translation_key": "Battery",
        "attribute": "battery_state",
        "unit": "%",
        "device_class": "battery",
        "icon": "mdi:battery",
        "state_class": "measurement"
    },
    {
        "key": "steps",
        "translation_key": "Steps",
        "attribute": "steps_state",
        "unit": "steps",
        "icon": "mdi:walk",
        "state_class": "total_increasing",
        # Acumulado de 7 días en extra_state_attributes: week_days (total por
        # día), week_total, week_average y week_best. Sale de las estadísticas
        # del recorder, que ya existen por el state_class de arriba.
        "week_extract": True
    },
    {
        "key": "steps_target",
        "translation_key": "Steps Daily Target",
        "attribute": "steps_daily_target",
        "unit": "steps",
        "icon": "mdi:flag-checkered",
        "state_class": "measurement",
        "entity_category": "diagnostic",
    },    
    {
        "key": "heart_rate",
        "translation_key": "Heart Rate",
        "attribute": "heart_state",
        "unit": "bpm",
        "device_class": "heart_rate",
        "icon": "mdi:heart-pulse",
        "state_class": "measurement"
    },
    {
        "key": "heart_max",
        "translation_key": "Heart Rate Max",
        "attribute": "heart_daily_summary",
        "unit": "bpm",
        "device_class": "heart_rate",
        "icon": "mdi:heart-flash",
        "state_class": "measurement",
        "json_extract": "maximum.hr_value"  
    },
    {
        "key": "heart_resting",
        "translation_key": "Resting Heart Rate",
        "attribute": "heart_resting",
        "unit": "bpm",
        "device_class": "heart_rate",
        "icon": "mdi:heart-pulse",
        "state_class": "measurement"
    },    
    {
        "key": "spo2",
        "translation_key": "Blood Oxygen",
        "attribute": "spo2_state",
        "unit": "%",
        "icon": "mdi:lungs",
        "state_class": "measurement",
        "json_extract": "value"
    },
    {
        "key": "calories",
        "translation_key": "Calories",
        "attribute": "calorie_state",
        "unit": "kcal",
        "icon": "mdi:fire",
        "state_class": "total_increasing",
        # Acumulado de 7 días en extra_state_attributes: week_days (total por
        # día), week_total, week_average y week_best. Sale de las estadísticas
        # del recorder, que ya existen por el state_class de arriba.
        "week_extract": True
    },
    {
        "key": "calories_target",
        "translation_key": "Calories Target",
        "attribute": "calories_burnt_target",
        "unit": "kcal",
        "icon": "mdi:fire-circle",
        "state_class": "measurement",
        "entity_category": "diagnostic",
    },    
    {
        "key": "distance",
        "translation_key": "Distance",
        "attribute": "distance_state",
        "unit": "m",
        "device_class": "distance",
        "icon": "mdi:map-marker-distance",
        "state_class": "total_increasing",
        # Acumulado de 7 días en extra_state_attributes: week_days (total por
        # día), week_total, week_average y week_best. Sale de las estadísticas
        # del recorder, que ya existen por el state_class de arriba.
        "week_extract": True
    },
    {
        "key": "stand_hours",
        "translation_key": "Stand Hours",
        "attribute": "stand_state",
        "unit": "h",
        "icon": "mdi:human",
        "state_class": "measurement",
        # Acumulado de 7 días en extra_state_attributes: week_days (total por
        # día), week_total, week_average y week_best. Sale de las estadísticas
        # del recorder, que ya existen por el state_class de arriba.
        "week_extract": True
    },
    {
        "key": "stand_hours_target",
        "translation_key": "Stand Hours Target",
        "attribute": "stand_hours_target",
        "unit": "h",
        "icon": "mdi:human-handsup",
        "state_class": "measurement",
        "entity_category": "diagnostic",
    },    
    {
        "key": "fat_burning",
        "translation_key": "Fat Burning",
        "attribute": "fat_burning_state",
        "unit": "min",
        "icon": "mdi:fire-circle",
        "state_class": "measurement",
        # Acumulado de 7 días en extra_state_attributes: week_days (total por
        # día), week_total, week_average y week_best. Sale de las estadísticas
        # del recorder, que ya existen por el state_class de arriba.
        "week_extract": True
    },
    {
        "key": "fat_burning_target",
        "translation_key": "Fat Burning Target",
        "attribute": "fat_burning_minutes_target",
        "unit": "min",
        "icon": "mdi:fire-circle",
        "state_class": "measurement",
        "entity_category": "diagnostic",
    },    
    {
        "key": "pai",
        "translation_key": "PAI Score",
        "attribute": "pai_state",
        "unit": "PAI",
        "icon": "mdi:chart-line",
        "state_class": "measurement",
        # 7-day daily mean/min/max in extra_state_attributes.last_week (see stress above).
        "trend_extract": True
    },
    {
        "key": "pai_total",
        "translation_key": "PAI Total",
        "attribute": "pai_total",
        "unit": "PAI",
        "icon": "mdi:chart-line",
        "state_class": "measurement"
    },
    {
        "key": "temperature",
        "translation_key": "Body Temperature",
        "attribute": "temperature_state",
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "state_class": "measurement",
        "json_extract": "value",
        "value_convert": 0.01  # ← 3318 * 0.01 = 33.18°C
    },
    {
        "key": "sleep_status",
        "translation_key": "Sleep Status",
        "attribute": "sleep_state",
        "icon": "mdi:sleep"
    },
    {
        "key": "sleep_score",
        "translation_key": "Sleep Score",
        "attribute": "sleep_info",
        "unit": "points",
        "icon": "mdi:sleep",
        "state_class": "measurement",
        "json_extract": "score"
    },
    {
        "key": "sleep_total_time",
        "translation_key": "Sleep Total Time", 
        "attribute": "sleep_info",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:bed-clock",
        "state_class": "measurement",
        "json_extract": "totalTime"
    },
    {
        "key": "sleep_deep_time",
        "translation_key": "Sleep Deep Time",
        "attribute": "sleep_info",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:bed",
        "state_class": "measurement",
        "json_extract": "deepTime"
    },
    {
        "key": "sleep_start_time",
        "translation_key": "Sleep Start Time",
        "attribute": "sleep_info",
        "icon": "mdi:weather-night",
        "json_extract": "startTime",
        "time_convert": True   
    },
    {
        "key": "sleep_end_time",
        "translation_key": "Sleep End Time",
        "attribute": "sleep_info",
        "icon": "mdi:weather-sunny",
        "json_extract": "endTime",
        "time_convert": True   
    },
    {
        "key": "sleep_deep_minutes",
        "translation_key": "Sleep Deep Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:sleep",
        "state_class": "measurement",
        "sleep_stage_extract": "DEEP_STAGE"
    },
    {
        "key": "sleep_rem_minutes",
        "translation_key": "Sleep REM Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:brain",
        "state_class": "measurement",
        "sleep_stage_extract": "REM_STAGE"
    },
    {
        "key": "sleep_light_minutes",
        "translation_key": "Sleep Light Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:weather-night-partly-cloudy",
        "state_class": "measurement",
        "sleep_stage_extract": "LIGHT_STAGE"
    },
    {
        "key": "sleep_wake_minutes",
        "translation_key": "Sleep Wake Stage",
        "attribute": "sleep_stage_data",
        "unit": "min",
        "device_class": "duration",
        "icon": "mdi:eye",
        "state_class": "measurement",
        "sleep_stage_extract": "WAKE_STAGE"
    },
    {
        # State = total minutes of the last sleep session (sum of every segment's
        # duration_min — a bare segment count meant nothing on a dashboard, confirmed
        # confusing a real user). extra_state_attributes.timeline is the per-cycle
        # breakdown (phase name + start/stop HH:MM + duration_min) and segment_count,
        # built from the same raw sleep_stage_data ({model, start, stop}
        # minutes-since-midnight) the sleep_*_minutes sensors above already sum.
        # See WatchSleepTimelineSensor.
        "key": "sleep_timeline",
        "translation_key": "sleep_timeline",
        "attribute": "sleep_stage_data",
        "icon": "mdi:timeline-clock-outline",
        "unit": "min",
        "device_class": "duration",
        "state_class": "measurement",
        "sleep_timeline_extract": True,
    },
    {
        "key": "stress",
        "attribute": "stress_state",
        "icon": "mdi:emoticon-happy",
        "state_class": "measurement",
        "json_extract": "value",
        # 7-day daily mean/min/max in extra_state_attributes.last_week, from HA's own
        # recorder statistics (this sensor already has state_class: measurement, so HA
        # records daily long-term stats for it automatically — no watch-side change).
        "trend_extract": True
    },
    {
        "key": "wear",
        "attribute": "wear_state",
        "icon": "mdi:watch",
        "lookup_table": WEAR_STATES,
    },
    {
        "key": "user_age",
        "translation_key": "Age",
        "attribute": "user_age",
        "icon": "mdi:account",
        "entity_category": "diagnostic",
    },
    {
        "key": "user_height",
        "translation_key": "Height",
        "attribute": "user_height",
        "icon": "mdi:human-male-height",
        "unit": "cm",
        "entity_category": "diagnostic",
    },
    {
        "key": "user_weight",
        "translation_key": "Weight",
        "attribute": "user_weight",
        "icon": "mdi:weight-kilogram",
        "unit": "kg",
        "entity_category": "diagnostic",
    },
    {
        "key": "user_gender",
        "translation_key": "Gender",
        "attribute": "user_gender",
        "icon": "mdi:gender-male-female",
        "entity_category": "diagnostic",
    },
    {
        "key": "user_region",
        "translation_key": "Region",
        "attribute": "user_region",
        "icon": "mdi:earth",
        "entity_category": "diagnostic",
    },
    {
        "key": "workout_last_date",
        "translation_key": "Last Workout Date",
        "attribute": "workout_last_date",
        "icon": "mdi:calendar-clock",
        "device_class": "timestamp",
        "iso_timestamp": True,
        "entity_category": "diagnostic",
    },
    {
        "key": "workout_last_duration",
        "translation_key": "Last Workout Duration",
        "attribute": "workout_last_duration",
        "icon": "mdi:timer-outline",
        "unit": "min",
    },
    {
        "key": "workout_last_sport_type",
        "translation_key": "Last Sport Type",
        "attribute": "workout_last_sport_type",
        "icon": "mdi:run",
    },
    {
        "key": "workout_training_load",
        "translation_key": "Training Load",
        "attribute": "workout_training_load",
        "icon": "mdi:weight-lifter",
    },
    {
        "key": "workout_vo2_max",
        "translation_key": "VO2 Max",
        "attribute": "workout_vo2_max",
        "icon": "mdi:lungs",
        "unit": "ml/kg/min",
    },
    {
        "key": "workout_count",
        "translation_key": "Workout Count",
        "attribute": "workout_count",
        "icon": "mdi:counter",
    },
    {
        "key": "workout_history",
        "translation_key": "workout_history",
        "attribute": "workout_history",
        "icon": "mdi:history",
        "workout_history_extract": True,
    },
    {
        "key": "altitude_state",
        "translation_key": "altitude_state",
        "attribute": "altitude_state",
        "icon": "mdi:elevation-rise",
        "unit": "m",
    },
    {
        "key": "air_pressure_state",
        "translation_key": "air_pressure_state",
        "attribute": "air_pressure_state",
        "icon": "mdi:gauge",
        "unit": "hPa",
    },
    { 
        "key": "os_version", 
        "translation_key": "os_version", 
        "attribute": "os_version", 
        "icon": "mdi:cog", 
        "entity_category": "diagnostic" 
    },
    { 
        "key": "firmware_version", 
        "translation_key": "firmware_version",
        "attribute": "firmware_version", 
        "icon": "mdi:chip",
        "entity_category": "diagnostic"
    },
    {
        "key": "min_api",
        "translation_key": "min_api",
        "attribute": "min_api",
        "icon": "mdi:api",
        "entity_category": "diagnostic"
    },
    {
        "key": "app_version",
        "translation_key": "app_version",
        "attribute": "app_version",
        "icon": "mdi:cellphone-arrow-down",
        "entity_category": "diagnostic"
    },
    {
        "key": "record_time",
        "translation_key": "record_time",
        "attribute": "record_time",
        "icon": "mdi:clock-check-outline",
        "device_class": "timestamp",
        "entity_category": "diagnostic",
        "iso_timestamp": True
    },
    {
        "key": "sync_age",
        "translation_key": "Sync Age",
        # Se calcula a partir de record_time, no de un atributo propio: el reloj
        # no manda "cuánto hace", manda "cuándo fue".
        "attribute": "record_time",
        "unit": "min",
        "icon": "mdi:sync-alert",
        "state_class": "measurement",
        # Este sensor se recalcula solo cada minuto. Todos los demás son pasivos
        # y solo cambian cuando el reloj envía, así que una app parada pasaba
        # inadvertida: el panel seguía enseñando los datos de la mañana como si
        # fueran de ahora. Aquí el número crece cuando el reloj calla.
        "sync_age_extract": True,
        "stale_after_minutes": 60
    },
    {
        "key": "update_source",
        "translation_key": "update_source",
        "attribute": "update_source",
        "icon": "mdi:sync",
        "entity_category": "diagnostic"
    },
    {
        "key": "workout_full_recovery_time",
        "translation_key": "workout_full_recovery_time",
        "attribute": "workout_full_recovery_time",
        "icon": "mdi:timer-refresh-outline",
        "unit": "h",
        "state_class": "measurement"
    },
    {
        "key": "screen_brightness",
        "translation_key": "screen_brightness",
        "attribute": "screen_brightness",
        "icon": "mdi:brightness-6",
        "unit": "%",
        "state_class": "measurement",
        "entity_category": "diagnostic"
    },
    {
        "key": "device_name",
        "translation_key": "device_name",
        "attribute": "device_name",
        "icon": "mdi:watch",
        "entity_category": "diagnostic"
    },
    {
        "key": "user_nick_name",
        "translation_key": "user_nick_name",
        "attribute": "user_nick_name",
        "icon": "mdi:account-circle",
        "entity_category": "diagnostic"
    },
    {
        "key": "disk_free",
        "translation_key": "disk_free",
        "attribute": "disk_info",
        "icon": "mdi:harddisk",
        "unit": "MB",
        "state_class": "measurement",
        "entity_category": "diagnostic",
        "json_extract": "free",
        "disk_convert": True
    },
    {
        "key": "disk_total",
        "translation_key": "disk_total",
        "attribute": "disk_info",
        "icon": "mdi:harddisk",
        "unit": "MB",
        "state_class": "measurement",
        "entity_category": "diagnostic",
        "json_extract": "total",
        "disk_convert": True
    },
]

BINARY_SENSORS = [
    {
        # Zepp OS has no native "is charging" flag (checked: the Battery sensor only
        # exposes getCurrent()), so this is inferred from the battery_state delta
        # between consecutive master-sensor updates. See WatchChargingBinarySensor.
        "key": "is_charging",
        "translation_key": "is_charging",
        "attribute": "battery_state",
        "icon": "mdi:battery-charging",
        "device_class": "battery_charging",
        "charging_extract": True,
    },
    {
        "key": "system_mode_dnd",
        "translation_key": "system_mode_dnd", 
        "attribute": "system_mode_dnd", 
        "icon": "mdi:minus-circle", 
    },
    { 
        "key": "system_mode_sleep", 
        "translation_key": "system_mode_sleep", 
        "attribute": "system_mode_sleep", 
        "icon": "mdi:sleep", 
    },
    { 
        "key": "system_mode_theater", 
        "translation_key": "system_mode_theater", 
        "attribute": "system_mode_theater", 
        "icon": "mdi:movie", 
    },
    { 
        "key": "system_mode_power_saving", 
        "translation_key": "system_mode_power_saving", 
        "attribute": "system_mode_power_saving", 
        "icon": "mdi:battery-low", 
    },
    {
        "key": "system_mode_ultra_power_saving",
        "translation_key": "system_mode_ultra_power_saving",
        "attribute": "system_mode_ultra_power_saving",
        "icon": "mdi:battery-outline",
    },
    {
        "key": "screen_aod_mode",
        "translation_key": "screen_aod_mode",
        "attribute": "screen_aod_mode",
        "icon": "mdi:overscan",
    },
    {
        "key": "is_sleeping",
        "translation_key": "is_sleeping",
        "attribute": "sleep_state",
        "icon": "mdi:sleep",
        "true_value": "Sleeping",
    },
    {
        "key": "is_moving",
        "translation_key": "is_moving",
        "attribute": "wear_state",
        "icon": "mdi:motion-sensor",
        "device_class": "motion",
        "true_value": 2,
    },
    {
        "key": "device_nfc",
        "translation_key": "device_nfc",
        "attribute": "device_nfc",
        "icon": "mdi:nfc",
        "entity_category": "diagnostic",
    },
    {
        "key": "device_mic",
        "translation_key": "device_mic",
        "attribute": "device_mic",
        "icon": "mdi:microphone",
        "entity_category": "diagnostic",
    },
    {
        "key": "device_crown",
        "translation_key": "device_crown",
        "attribute": "device_crown",
        "icon": "mdi:rotate-3d-variant",
        "entity_category": "diagnostic",
    },
    {
        "key": "device_buzzer",
        "translation_key": "device_buzzer",
        "attribute": "device_buzzer",
        "icon": "mdi:bell-ring",
        "entity_category": "diagnostic",
    },
    {
        "key": "device_speaker",
        "translation_key": "device_speaker",
        "attribute": "device_speaker",
        "icon": "mdi:volume-high",
        "entity_category": "diagnostic",
    },
]


SPORT_TYPES = {
    1001: "Outdoor Running", 
    1002: "Treadmill", 
    1003: "Walking",
    1004: "Outdoor Cycling", 
    1005: "Free Training", 
    1006: "Pool Swimming",
    1007: "Open Water Swimming", 
    1008: "Indoor Riding", 
    1009: "Elliptical Machine",
    1010: "Mountaineering",
    1011: "Cross Country Running", 
    1012: "Skiing",
    1015: "Outdoor Hiking", 
    1017: "Tennis", 
    1018: "Football",
    1019: "Ironman Triathlon", 
    1020: "Compound Motion", 
    1021: "Jump Rope",
    1023: "Rowing Machine",
    1024: "Indoor Fitness", 
    1040: "Indoor Walking",
    1041: "Curling", 
    1042: "Snowboarding", 
    1043: "Alpine Skiing",
    1044: "Outdoor Skating", 
    1045: "Indoor Skating", 
    1046: "Cross-Country Skiing",
    1047: "Mountain Cycling", 
    1048: "BMX", 
    1049: "HIIT",
    1050: "Core Training", 
    1051: "Mixed Aerobic", 
    1052: "Strength Training",
    1053: "Stretching", 
    1054: "Climber", 
    1055: "Flexibility Training",
    1057: "Step Training", 
    1058: "Stepper", 
    1059: "Gymnastics",
    1060: "Yoga", 
    1061: "Pilates", 
    1062: "Surfing",
    1063: "Hunting", 
    1064: "Fishing", 
    1065: "Sailing",
    1066: "Outdoor Boating", 
    1067: "Skateboard", 
    1068: "Paddleboarding",
    1069: "Roller Skating", 
    1070: "Rock Climbing", 
    1071: "Ballet",
    1072: "Belly Dance", 
    1073: "Square Dance", 
    1074: "Street Dance",
    1075: "Ballroom Dance", 
    1076: "Dance", 
    1077: "Zumba",
    1078: "Cricket", 
    1079: "Baseball", 
    1080: "Bowling",
    1081: "Squash", 
    1082: "Rugby", 
    1083: "Golf",
    1084: "Golf Swing",
    1085: "Basketball", 
    1086: "Softball",
    1087: "Gateball", 
    1088: "Volleyball", 
    1089: "Ping Pong",
    1090: "Hockey", 
    1091: "Handball", 
    1092: "Badminton",
    1093: "Archery", 
    1094: "Equestrian Sports", 
    1095: "Swordsmanship",
    1096: "Karate", 
    1097: "Boxing", 
    1098: "Judo",
    1099: "Wrestling", 
    1100: "Tai Chi", 
    1101: "Muay Thai",
    1102: "Taekwondo", 
    1103: "Martial Arts", 
    1104: "Free Fighting",
    1105: "Snowboarding", 
    1106: "Kitesurfing", 
    1108: "Climb the Stairs",
    1109: "Fitness", 
    1110: "Orienteering", 
    1111: "Group Exercise",
    1112: "Latin Dance", 
    1113: "Jazz Dance", 
    1114: "Combat Exercise",
    1115: "Hula Hoop", 
    1116: "Frisbee", 
    1117: "Dart",
    1118: "Flying a Kite",
    1119: "Tug-of-war", 
    1120: "Kicking Shuttlecock",
    1121: "Beach Football",
    1122: "Beach Volleyball", 
    1123: "Drifting",
    1124: "Motorboat", 
    1125: "Bicycle", 
    1126: "Sled",
    1128: "Winter Biathlon", 
    1129: "Parkour", 
    1130: "Cross-training",
    1131: "Race Walking", 
    1132: "Driving", 
    1133: "Paragliding",
    1134: "One Minute Sit-ups", 
    1135: "One Minute Skipping Rope",
    1136: "Snowmobile", 
    1137: "Off-Road Motorcycle", 
    1138: "Dragon Boat",
    1139: "Water Ski", 
    1140: "Kayaking", 
    1141: "Rowing",
    1142: "Polo", 
    1143: "Spinning Bike",
    1144: "Walking Machine",
    1145: "Racquetball", 
    1146: "Folk Dance", 
    1147: "Jiu-Jitsu",
    1148: "Fencing", 
    1149: "Horizontal Bar", 
    1150: "Parallel Bars",
    1151: "Billiards", 
    1152: "Sepak Takraw", 
    1153: "Dodgeball",
    1154: "Water Polo", 
    1155: "Fin Swimming", 
    1156: "Synchronized Swimming",
    1157: "Snorkeling", 
    1158: "Ice Hockey", 
    1159: "Swing",
    1160: "Shuffleboard", 
    1161: "Table Football", 
    1162: "Shuttlecock",
    1163: "Somatosensory Games", 
    1164: "Indoor Football", 
    1165: "Hip Hop Dance",
    1166: "Pole Dance", 
    1167: "Battle Rope", 
    1168: "Break Dance",
    1169: "Sandbag Ball", 
    1170: "Bocce", 
    1171: "Pull Back the Ball",
    1172: "Indoor Surfing", 
    1173: "Chess", 
    1174: "Checkers",
    1175: "Go", 
    1176: "Bridge", 
    1177: "Board Game",
    1178: "Snowshoe Hiking", 
    1179: "Shooting", 
    1180: "Skydiving",
    1181: "Downhill", 
    1182: "Bungee Jumping", 
    1183: "Trampoline",
    1184: "Bouldering", 
    1185: "Modern Dance", 
    1186: "Disco",
    1187: "Tap Dance",
    1188: "Floor Ball", 
    1189: "Electronic Sports",
    1190: "ATV",
    1191: "Football (without GPS)", 
    1192: "Playground Running",
    1193: "Fishing (Number of Fishes)",
    1194: "Indoor Rock Climbing",
    1195: "Mountaineering and Skiing",
    1196: "Outdoor Freediving",
    1197: "Indoor Freediving", 
    1198: "Fishing and Hunting",
    1199: "Simple Tennis", 
    1200: "Wakewave Surfing",
    1201: "Surfing (identify number of trips)",
    1202: "Kitesurfing (Identification Gliding)", 
    1203: "Ultra Marathon",
    # Zepp sigue añadiendo deportes en las actualizaciones del reloj y la tabla
    # se queda corta: 1215 llegó desde un entrenamiento real y salía como
    # "Unknown (1215)". Si aparece otro código sin nombre, es esto.
    1215: "Walking the Dog",
    1222: "Hyrox",
}

# Nombres de deporte en español. SPORT_TYPES viene del SDK de Zepp y está en
# inglés; esto lo traduce igual que SLEEP_PHASE_LABELS hace con las fases del
# sueño. Lo que no esté aquí se queda en inglés en vez de romperse.
SPORT_TYPE_LABELS = {
    "es": {
        "ATV": "Quad",
        "Alpine Skiing": "Esquí alpino",
        "Archery": "Tiro con arco",
        "BMX": "BMX",
        "Badminton": "Bádminton",
        "Ballet": "Ballet",
        "Ballroom Dance": "Baile de salón",
        "Baseball": "Béisbol",
        "Basketball": "Baloncesto",
        "Battle Rope": "Cuerda de batalla",
        "Beach Football": "Fútbol playa",
        "Beach Volleyball": "Vóley playa",
        "Belly Dance": "Danza del vientre",
        "Bicycle": "Bicicleta",
        "Billiards": "Billar",
        "Board Game": "Juego de mesa",
        "Bocce": "Petanca",
        "Bouldering": "Búlder",
        "Bowling": "Bolos",
        "Boxing": "Boxeo",
        "Break Dance": "Breakdance",
        "Bridge": "Bridge",
        "Bungee Jumping": "Puenting",
        "Checkers": "Damas",
        "Chess": "Ajedrez",
        "Climb the Stairs": "Subir escaleras",
        "Climber": "Escalador",
        "Combat Exercise": "Ejercicio de combate",
        "Compound Motion": "Movimiento compuesto",
        "Core Training": "Entrenamiento de core",
        "Cricket": "Críquet",
        "Cross Country Running": "Campo a través",
        "Cross-Country Skiing": "Esquí de fondo",
        # "Cross-training" se deja sin traducir a propósito (2026-09-04, petición
        # de usuario): "Entrenamiento cruzado" se confundía con CrossFit, que es
        # una marca y una metodología distinta.
        "Curling": "Curling",
        "Dance": "Baile",
        "Dart": "Dardos",
        "Disco": "Disco",
        "Dodgeball": "Balón prisionero",
        "Downhill": "Descenso",
        "Dragon Boat": "Barco dragón",
        "Drifting": "Drifting",
        "Driving": "Conducir",
        "Electronic Sports": "Deportes electrónicos",
        "Elliptical Machine": "Elíptica",
        "Equestrian Sports": "Hípica",
        "Fencing": "Esgrima",
        "Fin Swimming": "Natación con aletas",
        "Fishing": "Pesca",
        "Fishing (Number of Fishes)": "Pesca (número de capturas)",
        "Fishing and Hunting": "Pesca y caza",
        "Fitness": "Fitness",
        "Flexibility Training": "Entrenamiento de flexibilidad",
        "Floor Ball": "Floorball",
        "Flying a Kite": "Volar cometa",
        "Folk Dance": "Danza folclórica",
        "Football": "Fútbol",
        "Football (without GPS)": "Fútbol (sin GPS)",
        "Free Fighting": "Combate libre",
        "Free Training": "Entrenamiento libre",
        "Frisbee": "Frisbee",
        "Gateball": "Gateball",
        "Go": "Go",
        "Golf": "Golf",
        "Golf Swing": "Swing de golf",
        "Group Exercise": "Ejercicio en grupo",
        "Gymnastics": "Gimnasia",
        "HIIT": "HIIT",
        "Handball": "Balonmano",
        "Hip Hop Dance": "Baile hip hop",
        "Hockey": "Hockey",
        "Horizontal Bar": "Barra fija",
        "Hula Hoop": "Hula hoop",
        "Hunting": "Caza",
        "Ice Hockey": "Hockey sobre hielo",
        "Indoor Fitness": "Fitness en interior",
        "Indoor Football": "Fútbol sala",
        "Indoor Freediving": "Apnea en interior",
        "Indoor Riding": "Ciclismo en interior",
        "Indoor Rock Climbing": "Escalada en interior",
        "Indoor Skating": "Patinaje en interior",
        "Indoor Surfing": "Surf en interior",
        "Indoor Walking": "Caminar en interior",
        "Ironman Triathlon": "Triatlón Ironman",
        "Jazz Dance": "Danza jazz",
        "Jiu-Jitsu": "Jiu-jitsu",
        "Judo": "Judo",
        "Jump Rope": "Comba",
        "Karate": "Kárate",
        "Kayaking": "Kayak",
        "Kicking Shuttlecock": "Peteca",
        "Kitesurfing": "Kitesurf",
        "Kitesurfing (Identification Gliding)": "Kitesurf (planeo)",
        "Latin Dance": "Baile latino",
        "Martial Arts": "Artes marciales",
        "Mixed Aerobic": "Aeróbico mixto",
        "Modern Dance": "Danza moderna",
        "Motorboat": "Lancha motora",
        "Mountain Cycling": "Ciclismo de montaña",
        "Mountaineering": "Montañismo",
        "Mountaineering and Skiing": "Esquí de montaña",
        "Muay Thai": "Muay thai",
        "Off-Road Motorcycle": "Motocross",
        "One Minute Sit-ups": "Abdominales en un minuto",
        "One Minute Skipping Rope": "Comba en un minuto",
        "Open Water Swimming": "Natación en aguas abiertas",
        "Orienteering": "Orientación",
        "Outdoor Boating": "Navegación al aire libre",
        "Outdoor Cycling": "Ciclismo al aire libre",
        "Outdoor Freediving": "Apnea al aire libre",
        "Outdoor Hiking": "Senderismo",
        "Outdoor Running": "Correr al aire libre",
        "Outdoor Skating": "Patinaje al aire libre",
        "Paddleboarding": "Pádel surf",
        "Paragliding": "Parapente",
        "Parallel Bars": "Barras paralelas",
        "Parkour": "Parkour",
        "Pilates": "Pilates",
        "Ping Pong": "Tenis de mesa",
        "Playground Running": "Correr en pista",
        "Pole Dance": "Pole dance",
        "Polo": "Polo",
        "Pool Swimming": "Natación en piscina",
        "Pull Back the Ball": "Recogida de balón",
        "Race Walking": "Marcha atlética",
        "Racquetball": "Racquetball",
        "Rock Climbing": "Escalada en roca",
        "Roller Skating": "Patinaje sobre ruedas",
        "Rowing": "Remo",
        "Rowing Machine": "Remo en máquina",
        "Rugby": "Rugby",
        "Sailing": "Vela",
        "Sandbag Ball": "Balón de arena",
        "Sepak Takraw": "Sepak takraw",
        "Shooting": "Tiro",
        "Shuffleboard": "Shuffleboard",
        "Shuttlecock": "Volante",
        "Simple Tennis": "Tenis sencillo",
        "Skateboard": "Monopatín",
        "Skiing": "Esquí",
        "Skydiving": "Paracaidismo",
        "Sled": "Trineo",
        "Snorkeling": "Buceo con tubo",
        "Snowboarding": "Snowboard",
        "Snowmobile": "Moto de nieve",
        "Snowshoe Hiking": "Raquetas de nieve",
        "Softball": "Sóftbol",
        "Somatosensory Games": "Juegos de movimiento",
        "Spinning Bike": "Bicicleta de spinning",
        "Square Dance": "Baile en cuadrilla",
        "Squash": "Squash",
        "Step Training": "Step",
        "Stepper": "Stepper",
        "Street Dance": "Baile urbano",
        "Strength Training": "Fuerza",
        "Stretching": "Estiramientos",
        "Surfing": "Surf",
        "Surfing (identify number of trips)": "Surf (cuenta de olas)",
        "Swing": "Columpio",
        "Swordsmanship": "Esgrima tradicional",
        "Synchronized Swimming": "Natación sincronizada",
        "Table Football": "Futbolín",
        "Taekwondo": "Taekwondo",
        "Tai Chi": "Taichí",
        "Tap Dance": "Claqué",
        "Tennis": "Tenis",
        "Trampoline": "Cama elástica",
        "Treadmill": "Cinta de correr",
        "Tug-of-war": "Sogatira",
        "Ultra Marathon": "Ultramaratón",
        "Volleyball": "Voleibol",
        "Wakewave Surfing": "Wakesurf",
        "Walking": "Caminar",
        "Walking the Dog": "Pasear al perro",
        "Walking Machine": "Cinta de caminar",
        "Water Polo": "Waterpolo",
        "Water Ski": "Esquí acuático",
        "Winter Biathlon": "Biatlón de invierno",
        "Wrestling": "Lucha",
        "Yoga": "Yoga",
        "Zumba": "Zumba",
    },
    "fr": {
        "ATV": "Quad",
        "Alpine Skiing": "Ski alpin",
        "Archery": "Tir à l'arc",
        "BMX": "BMX",
        "Badminton": "Badminton",
        "Ballet": "Ballet",
        "Ballroom Dance": "Danse de salon",
        "Baseball": "Baseball",
        "Basketball": "Basketball",
        "Battle Rope": "Corde ondulatoire",
        "Beach Football": "Beach soccer",
        "Beach Volleyball": "Beach-volley",
        "Belly Dance": "Danse orientale",
        "Bicycle": "Vélo",
        "Billiards": "Billard",
        "Board Game": "Jeu de société",
        "Bocce": "Pétanque",
        "Bouldering": "Bloc (escalade)",
        "Bowling": "Bowling",
        "Boxing": "Boxe",
        "Break Dance": "Breakdance",
        "Bridge": "Bridge",
        "Bungee Jumping": "Saut à l'élastique",
        "Checkers": "Dames",
        "Chess": "Échecs",
        "Climb the Stairs": "Monter les escaliers",
        "Climber": "Grimpeur (appareil)",
        "Combat Exercise": "Exercice de combat",
        "Compound Motion": "Mouvement composé",
        "Core Training": "Renforcement du gainage",
        "Cricket": "Cricket",
        "Cross Country Running": "Cross-country",
        "Cross-Country Skiing": "Ski de fond",
        "Curling": "Curling",
        "Dance": "Danse",
        "Dart": "Fléchettes",
        "Disco": "Disco",
        "Dodgeball": "Ballon prisonnier",
        "Downhill": "Descente",
        "Dragon Boat": "Bateau-dragon",
        "Drifting": "Drift",
        "Driving": "Conduite",
        "Electronic Sports": "Sports électroniques",
        "Elliptical Machine": "Vélo elliptique",
        "Equestrian Sports": "Équitation",
        "Fencing": "Escrime",
        "Fin Swimming": "Nage avec palmes",
        "Fishing": "Pêche",
        "Fishing (Number of Fishes)": "Pêche (nombre de prises)",
        "Fishing and Hunting": "Pêche et chasse",
        "Fitness": "Fitness",
        "Flexibility Training": "Entraînement de la souplesse",
        "Floor Ball": "Floorball",
        "Flying a Kite": "Cerf-volant",
        "Folk Dance": "Danse folklorique",
        "Football": "Football",
        "Football (without GPS)": "Football (sans GPS)",
        "Free Fighting": "Combat libre",
        "Free Training": "Entraînement libre",
        "Frisbee": "Frisbee",
        "Gateball": "Gateball",
        "Go": "Go",
        "Golf": "Golf",
        "Golf Swing": "Swing de golf",
        "Group Exercise": "Exercice en groupe",
        "Gymnastics": "Gymnastique",
        "HIIT": "HIIT",
        "Handball": "Handball",
        "Hip Hop Dance": "Danse hip-hop",
        "Hockey": "Hockey",
        "Horizontal Bar": "Barre fixe",
        "Hula Hoop": "Hula hoop",
        "Hunting": "Chasse",
        "Ice Hockey": "Hockey sur glace",
        "Indoor Fitness": "Fitness en salle",
        "Indoor Football": "Futsal",
        "Indoor Freediving": "Apnée en piscine",
        "Indoor Riding": "Vélo en salle",
        "Indoor Rock Climbing": "Escalade en salle",
        "Indoor Skating": "Patinage en salle",
        "Indoor Surfing": "Surf en salle",
        "Indoor Walking": "Marche en intérieur",
        "Ironman Triathlon": "Triathlon Ironman",
        "Jazz Dance": "Danse jazz",
        "Jiu-Jitsu": "Jiu-jitsu",
        "Judo": "Judo",
        "Jump Rope": "Corde à sauter",
        "Karate": "Karaté",
        "Kayaking": "Kayak",
        "Kicking Shuttlecock": "Jianzi",
        "Kitesurfing": "Kitesurf",
        "Kitesurfing (Identification Gliding)": "Kitesurf (vol plané)",
        "Latin Dance": "Danse latine",
        "Martial Arts": "Arts martiaux",
        "Mixed Aerobic": "Aérobic mixte",
        "Modern Dance": "Danse moderne",
        "Motorboat": "Bateau à moteur",
        "Mountain Cycling": "VTT",
        "Mountaineering": "Alpinisme",
        "Mountaineering and Skiing": "Ski-alpinisme",
        "Muay Thai": "Muay thaï",
        "Off-Road Motorcycle": "Motocross",
        "One Minute Sit-ups": "Abdominaux en une minute",
        "One Minute Skipping Rope": "Corde à sauter (une minute)",
        "Open Water Swimming": "Nage en eau libre",
        "Orienteering": "Course d'orientation",
        "Outdoor Boating": "Navigation de plaisance",
        "Outdoor Cycling": "Cyclisme en extérieur",
        "Outdoor Freediving": "Apnée en extérieur",
        "Outdoor Hiking": "Randonnée",
        "Outdoor Running": "Course en extérieur",
        "Outdoor Skating": "Patinage en extérieur",
        "Paddleboarding": "Paddle",
        "Paragliding": "Parapente",
        "Parallel Bars": "Barres parallèles",
        "Parkour": "Parkour",
        "Pilates": "Pilates",
        "Ping Pong": "Tennis de table",
        "Playground Running": "Course sur piste",
        "Pole Dance": "Pole dance",
        "Polo": "Polo",
        "Pool Swimming": "Natation en piscine",
        "Pull Back the Ball": "Récupération de balle",
        "Race Walking": "Marche athlétique",
        "Racquetball": "Racquetball",
        "Rock Climbing": "Escalade",
        "Roller Skating": "Patin à roulettes",
        "Rowing": "Aviron",
        "Rowing Machine": "Rameur (machine)",
        "Rugby": "Rugby",
        "Sailing": "Voile",
        "Sandbag Ball": "Ballon lesté",
        "Sepak Takraw": "Sepak takraw",
        "Shooting": "Tir",
        "Shuffleboard": "Shuffleboard",
        "Shuttlecock": "Volant",
        "Simple Tennis": "Tennis simplifié",
        "Skateboard": "Skateboard",
        "Skiing": "Ski",
        "Skydiving": "Parachutisme",
        "Sled": "Luge",
        "Snorkeling": "Snorkeling",
        "Snowboarding": "Snowboard",
        "Snowmobile": "Motoneige",
        "Snowshoe Hiking": "Raquette à neige",
        "Softball": "Softball",
        "Somatosensory Games": "Jeux de mouvement",
        "Spinning Bike": "Vélo de spinning",
        "Square Dance": "Danse carrée",
        "Squash": "Squash",
        "Step Training": "Step",
        "Stepper": "Stepper",
        "Street Dance": "Danse urbaine",
        "Strength Training": "Musculation",
        "Stretching": "Étirements",
        "Surfing": "Surf",
        "Surfing (identify number of trips)": "Surf (nombre de vagues)",
        "Swing": "Balançoire",
        "Swordsmanship": "Escrime traditionnelle",
        "Synchronized Swimming": "Natation synchronisée",
        "Table Football": "Baby-foot",
        "Taekwondo": "Taekwondo",
        "Tai Chi": "Tai-chi",
        "Tap Dance": "Claquettes",
        "Tennis": "Tennis",
        "Trampoline": "Trampoline",
        "Treadmill": "Tapis de course",
        "Tug-of-war": "Tir à la corde",
        "Ultra Marathon": "Ultra-marathon",
        "Volleyball": "Volleyball",
        "Wakewave Surfing": "Wakesurf",
        "Walking": "Marche",
        "Walking the Dog": "Promener le chien",
        "Walking Machine": "Tapis de marche",
        "Water Polo": "Water-polo",
        "Water Ski": "Ski nautique",
        "Winter Biathlon": "Biathlon d'hiver",
        "Wrestling": "Lutte",
        "Yoga": "Yoga",
        "Zumba": "Zumba",
    },
    "de": {
        "ATV": "Quad",
        "Alpine Skiing": "Alpinski",
        "Archery": "Bogenschießen",
        "BMX": "BMX",
        "Badminton": "Badminton",
        "Ballet": "Ballett",
        "Ballroom Dance": "Gesellschaftstanz",
        "Baseball": "Baseball",
        "Basketball": "Basketball",
        "Battle Rope": "Battle Rope",
        "Beach Football": "Beachsoccer",
        "Beach Volleyball": "Beachvolleyball",
        "Belly Dance": "Bauchtanz",
        "Bicycle": "Fahrrad",
        "Billiards": "Billard",
        "Board Game": "Brettspiel",
        "Bocce": "Boccia",
        "Bouldering": "Bouldern",
        "Bowling": "Bowling",
        "Boxing": "Boxen",
        "Break Dance": "Breakdance",
        "Bridge": "Bridge",
        "Bungee Jumping": "Bungee-Jumping",
        "Checkers": "Dame (Spiel)",
        "Chess": "Schach",
        "Climb the Stairs": "Treppensteigen",
        "Climber": "Climber (Gerät)",
        "Combat Exercise": "Kampftraining",
        "Compound Motion": "Komplexe Bewegung",
        "Core Training": "Core-Training",
        "Cricket": "Cricket",
        "Cross Country Running": "Geländelauf",
        "Cross-Country Skiing": "Skilanglauf",
        "Curling": "Curling",
        "Dance": "Tanz",
        "Dart": "Darts",
        "Disco": "Disco",
        "Dodgeball": "Völkerball",
        "Downhill": "Abfahrt",
        "Dragon Boat": "Drachenboot",
        "Drifting": "Driften",
        "Driving": "Autofahren",
        "Electronic Sports": "E-Sport",
        "Elliptical Machine": "Crosstrainer",
        "Equestrian Sports": "Reitsport",
        "Fencing": "Fechten",
        "Fin Swimming": "Flossenschwimmen",
        "Fishing": "Angeln",
        "Fishing (Number of Fishes)": "Angeln (Anzahl Fänge)",
        "Fishing and Hunting": "Angeln und Jagen",
        "Fitness": "Fitness",
        "Flexibility Training": "Beweglichkeitstraining",
        "Floor Ball": "Floorball",
        "Flying a Kite": "Drachensteigen",
        "Folk Dance": "Volkstanz",
        "Football": "Fußball",
        "Football (without GPS)": "Fußball (ohne GPS)",
        "Free Fighting": "Freikampf",
        "Free Training": "Freies Training",
        "Frisbee": "Frisbee",
        "Gateball": "Gateball",
        "Go": "Go",
        "Golf": "Golf",
        "Golf Swing": "Golfschwung",
        "Group Exercise": "Gruppentraining",
        "Gymnastics": "Turnen",
        "HIIT": "HIIT",
        "Handball": "Handball",
        "Hip Hop Dance": "Hip-Hop-Tanz",
        "Hockey": "Hockey",
        "Horizontal Bar": "Reck",
        "Hula Hoop": "Hula-Hoop",
        "Hunting": "Jagen",
        "Ice Hockey": "Eishockey",
        "Indoor Fitness": "Fitness (drinnen)",
        "Indoor Football": "Hallenfußball",
        "Indoor Freediving": "Apnoetauchen (drinnen)",
        "Indoor Riding": "Indoor-Radfahren",
        "Indoor Rock Climbing": "Klettern (Halle)",
        "Indoor Skating": "Inline-Skating (Halle)",
        "Indoor Surfing": "Indoor-Surfen",
        "Indoor Walking": "Gehen (drinnen)",
        "Ironman Triathlon": "Ironman-Triathlon",
        "Jazz Dance": "Jazz-Tanz",
        "Jiu-Jitsu": "Jiu-Jitsu",
        "Judo": "Judo",
        "Jump Rope": "Seilspringen",
        "Karate": "Karate",
        "Kayaking": "Kajakfahren",
        "Kicking Shuttlecock": "Federfußball",
        "Kitesurfing": "Kitesurfen",
        "Kitesurfing (Identification Gliding)": "Kitesurfen (Gleiten)",
        "Latin Dance": "Lateinamerikanischer Tanz",
        "Martial Arts": "Kampfkunst",
        "Mixed Aerobic": "Gemischtes Aerobic",
        "Modern Dance": "Moderner Tanz",
        "Motorboat": "Motorboot",
        "Mountain Cycling": "Mountainbiken",
        "Mountaineering": "Bergsteigen",
        "Mountaineering and Skiing": "Skibergsteigen",
        "Muay Thai": "Muay Thai",
        "Off-Road Motorcycle": "Motocross",
        "One Minute Sit-ups": "Sit-ups (1 Minute)",
        "One Minute Skipping Rope": "Seilspringen (1 Minute)",
        "Open Water Swimming": "Freiwasserschwimmen",
        "Orienteering": "Orientierungslauf",
        "Outdoor Boating": "Bootfahren (draußen)",
        "Outdoor Cycling": "Radfahren (draußen)",
        "Outdoor Freediving": "Apnoetauchen (draußen)",
        "Outdoor Hiking": "Wandern",
        "Outdoor Running": "Laufen (draußen)",
        "Outdoor Skating": "Inline-Skating (draußen)",
        "Paddleboarding": "Stand-up-Paddling",
        "Paragliding": "Gleitschirmfliegen",
        "Parallel Bars": "Barren",
        "Parkour": "Parkour",
        "Pilates": "Pilates",
        "Ping Pong": "Tischtennis",
        "Playground Running": "Laufen (Sportplatz)",
        "Pole Dance": "Poledance",
        "Polo": "Polo",
        "Pool Swimming": "Schwimmen (Becken)",
        "Pull Back the Ball": "Ballrückholen",
        "Race Walking": "Gehen (Leichtathletik)",
        "Racquetball": "Racquetball",
        "Rock Climbing": "Klettern",
        "Roller Skating": "Rollschuhlaufen",
        "Rowing": "Rudern",
        "Rowing Machine": "Rudergerät",
        "Rugby": "Rugby",
        "Sailing": "Segeln",
        "Sandbag Ball": "Sandsack-Ball",
        "Sepak Takraw": "Sepak Takraw",
        "Shooting": "Schießen",
        "Shuffleboard": "Shuffleboard",
        "Shuttlecock": "Federball",
        "Simple Tennis": "Einfaches Tennis",
        "Skateboard": "Skateboard",
        "Skiing": "Skifahren",
        "Skydiving": "Fallschirmspringen",
        "Sled": "Schlitten",
        "Snorkeling": "Schnorcheln",
        "Snowboarding": "Snowboarden",
        "Snowmobile": "Schneemobil",
        "Snowshoe Hiking": "Schneeschuhwandern",
        "Softball": "Softball",
        "Somatosensory Games": "Bewegungsspiele",
        "Spinning Bike": "Spinning-Rad",
        "Square Dance": "Square Dance",
        "Squash": "Squash",
        "Step Training": "Step-Aerobic",
        "Stepper": "Stepper",
        "Street Dance": "Streetdance",
        "Strength Training": "Krafttraining",
        "Stretching": "Dehnen",
        "Surfing": "Surfen",
        "Surfing (identify number of trips)": "Surfen (Wellenzahl)",
        "Swing": "Schaukel",
        "Swordsmanship": "Schwertkampf",
        "Synchronized Swimming": "Synchronschwimmen",
        "Table Football": "Tischfußball",
        "Taekwondo": "Taekwondo",
        "Tai Chi": "Tai-Chi",
        "Tap Dance": "Stepptanz",
        "Tennis": "Tennis",
        "Trampoline": "Trampolin",
        "Treadmill": "Laufband",
        "Tug-of-war": "Tauziehen",
        "Ultra Marathon": "Ultramarathon",
        "Volleyball": "Volleyball",
        "Wakewave Surfing": "Wakesurfen",
        "Walking": "Gehen",
        "Walking the Dog": "Gassi gehen",
        "Walking Machine": "Gehband",
        "Water Polo": "Wasserball",
        "Water Ski": "Wasserski",
        "Winter Biathlon": "Winterbiathlon",
        "Wrestling": "Ringen",
        "Yoga": "Yoga",
        "Zumba": "Zumba",
    },
    "it": {
        "ATV": "Quad",
        "Alpine Skiing": "Sci alpino",
        "Archery": "Tiro con l'arco",
        "BMX": "BMX",
        "Badminton": "Badminton",
        "Ballet": "Balletto",
        "Ballroom Dance": "Danza da sala",
        "Baseball": "Baseball",
        "Basketball": "Pallacanestro",
        "Battle Rope": "Corda ondulatoria",
        "Beach Football": "Calcio da spiaggia",
        "Beach Volleyball": "Beach volley",
        "Belly Dance": "Danza del ventre",
        "Bicycle": "Bicicletta",
        "Billiards": "Biliardo",
        "Board Game": "Gioco da tavolo",
        "Bocce": "Bocce",
        "Bouldering": "Boulder",
        "Bowling": "Bowling",
        "Boxing": "Pugilato",
        "Break Dance": "Breakdance",
        "Bridge": "Bridge",
        "Bungee Jumping": "Bungee jumping",
        "Checkers": "Dama",
        "Chess": "Scacchi",
        "Climb the Stairs": "Salire le scale",
        "Climber": "Climber (attrezzo)",
        "Combat Exercise": "Esercizio di combattimento",
        "Compound Motion": "Movimento composto",
        "Core Training": "Allenamento core",
        "Cricket": "Cricket",
        "Cross Country Running": "Corsa campestre",
        "Cross-Country Skiing": "Sci di fondo",
        "Curling": "Curling",
        "Dance": "Danza",
        "Dart": "Freccette",
        "Disco": "Disco",
        "Dodgeball": "Palla avvelenata",
        "Downhill": "Discesa",
        "Dragon Boat": "Barca drago",
        "Drifting": "Drifting",
        "Driving": "Guida",
        "Electronic Sports": "Sport elettronici",
        "Elliptical Machine": "Ellittica",
        "Equestrian Sports": "Equitazione",
        "Fencing": "Scherma",
        "Fin Swimming": "Nuoto pinnato",
        "Fishing": "Pesca",
        "Fishing (Number of Fishes)": "Pesca (numero di catture)",
        "Fishing and Hunting": "Pesca e caccia",
        "Fitness": "Fitness",
        "Flexibility Training": "Allenamento della flessibilità",
        "Floor Ball": "Floorball",
        "Flying a Kite": "Aquilone",
        "Folk Dance": "Danza popolare",
        "Football": "Calcio",
        "Football (without GPS)": "Calcio (senza GPS)",
        "Free Fighting": "Combattimento libero",
        "Free Training": "Allenamento libero",
        "Frisbee": "Frisbee",
        "Gateball": "Gateball",
        "Go": "Go",
        "Golf": "Golf",
        "Golf Swing": "Swing da golf",
        "Group Exercise": "Esercizio di gruppo",
        "Gymnastics": "Ginnastica",
        "HIIT": "HIIT",
        "Handball": "Pallamano",
        "Hip Hop Dance": "Danza hip hop",
        "Hockey": "Hockey",
        "Horizontal Bar": "Sbarra",
        "Hula Hoop": "Hula hoop",
        "Hunting": "Caccia",
        "Ice Hockey": "Hockey su ghiaccio",
        "Indoor Fitness": "Fitness al chiuso",
        "Indoor Football": "Calcio a 5",
        "Indoor Freediving": "Apnea al chiuso",
        "Indoor Riding": "Ciclismo indoor",
        "Indoor Rock Climbing": "Arrampicata indoor",
        "Indoor Skating": "Pattinaggio indoor",
        "Indoor Surfing": "Surf indoor",
        "Indoor Walking": "Camminata al chiuso",
        "Ironman Triathlon": "Triathlon Ironman",
        "Jazz Dance": "Danza jazz",
        "Jiu-Jitsu": "Jiu-jitsu",
        "Judo": "Judo",
        "Jump Rope": "Corda per saltare",
        "Karate": "Karate",
        "Kayaking": "Kayak",
        "Kicking Shuttlecock": "Jianzi",
        "Kitesurfing": "Kitesurf",
        "Kitesurfing (Identification Gliding)": "Kitesurf (planata)",
        "Latin Dance": "Danza latina",
        "Martial Arts": "Arti marziali",
        "Mixed Aerobic": "Aerobica mista",
        "Modern Dance": "Danza moderna",
        "Motorboat": "Motoscafo",
        "Mountain Cycling": "Mountain bike",
        "Mountaineering": "Alpinismo",
        "Mountaineering and Skiing": "Sci alpinismo",
        "Muay Thai": "Muay thai",
        "Off-Road Motorcycle": "Motocross",
        "One Minute Sit-ups": "Addominali in un minuto",
        "One Minute Skipping Rope": "Corda in un minuto",
        "Open Water Swimming": "Nuoto in acque libere",
        "Orienteering": "Orientamento",
        "Outdoor Boating": "Navigazione all'aperto",
        "Outdoor Cycling": "Ciclismo all'aperto",
        "Outdoor Freediving": "Apnea all'aperto",
        "Outdoor Hiking": "Escursionismo",
        "Outdoor Running": "Corsa all'aperto",
        "Outdoor Skating": "Pattinaggio all'aperto",
        "Paddleboarding": "Sup (stand up paddle)",
        "Paragliding": "Parapendio",
        "Parallel Bars": "Parallele",
        "Parkour": "Parkour",
        "Pilates": "Pilates",
        "Ping Pong": "Tennis da tavolo",
        "Playground Running": "Corsa in pista",
        "Pole Dance": "Pole dance",
        "Polo": "Polo",
        "Pool Swimming": "Nuoto in piscina",
        "Pull Back the Ball": "Recupero palla",
        "Race Walking": "Marcia",
        "Racquetball": "Racquetball",
        "Rock Climbing": "Arrampicata",
        "Roller Skating": "Pattinaggio a rotelle",
        "Rowing": "Canottaggio",
        "Rowing Machine": "Vogatore (attrezzo)",
        "Rugby": "Rugby",
        "Sailing": "Vela",
        "Sandbag Ball": "Palla di sabbia",
        "Sepak Takraw": "Sepak takraw",
        "Shooting": "Tiro",
        "Shuffleboard": "Shuffleboard",
        "Shuttlecock": "Volano",
        "Simple Tennis": "Tennis semplificato",
        "Skateboard": "Skateboard",
        "Skiing": "Sci",
        "Skydiving": "Paracadutismo",
        "Sled": "Slittino",
        "Snorkeling": "Snorkeling",
        "Snowboarding": "Snowboard",
        "Snowmobile": "Motoslitta",
        "Snowshoe Hiking": "Racchette da neve",
        "Softball": "Softball",
        "Somatosensory Games": "Giochi di movimento",
        "Spinning Bike": "Spinning",
        "Square Dance": "Danza quadrata",
        "Squash": "Squash",
        "Step Training": "Step",
        "Stepper": "Stepper",
        "Street Dance": "Danza urbana",
        "Strength Training": "Forza",
        "Stretching": "Stretching",
        "Surfing": "Surf",
        "Surfing (identify number of trips)": "Surf (conteggio onde)",
        "Swing": "Altalena",
        "Swordsmanship": "Scherma tradizionale",
        "Synchronized Swimming": "Nuoto sincronizzato",
        "Table Football": "Calcio balilla",
        "Taekwondo": "Taekwondo",
        "Tai Chi": "Tai chi",
        "Tap Dance": "Tip tap",
        "Tennis": "Tennis",
        "Trampoline": "Trampolino",
        "Treadmill": "Tapis roulant",
        "Tug-of-war": "Tiro alla fune",
        "Ultra Marathon": "Ultramaratona",
        "Volleyball": "Pallavolo",
        "Wakewave Surfing": "Wakesurf",
        "Walking": "Camminata",
        "Walking the Dog": "Portare a spasso il cane",
        "Walking Machine": "Tapis roulant (camminata)",
        "Water Polo": "Pallanuoto",
        "Water Ski": "Sci nautico",
        "Winter Biathlon": "Biathlon invernale",
        "Wrestling": "Lotta",
        "Yoga": "Yoga",
        "Zumba": "Zumba",
    },
}

# Patch lookup_table into configs that depend on dicts defined after SENSORS
for _s in SENSORS:
    if _s["key"] == "workout_last_sport_type":
        _s["lookup_table"] = SPORT_TYPES
        break

